@startuml

!define AZPUML https://raw.githubusercontent.com/seesharprun/AZURE-PlantUML/master/dist/

!includeurl AZPUML/common.puml
!includeurl AZPUML/SQLDatabase/SQLDatabase.puml

SQLDATABASE(local_account)
SQLDATABASE(partner_account, "Partner's Database")

local_account <-- partner_account

@enduml
